import logoMark from "../../assets/logoMark.js";
import { formatDate } from "../../lib/format.js";

const FIELD_ORDER = [
  ["manpower", "Manpower"],
  ["equipment", "Equipment"],
  ["completed_activities", "Completed Activities"],
  ["quantities", "Quantities Executed"],
  ["materials_received", "Materials Received"],
  ["delays", "Delays"],
  ["site_issues", "Site Issues"],
  ["safety_observations", "Safety Observations"],
  ["required_actions", "Required Actions"],
  ["tomorrow_plan", "Tomorrow's Plan"],
];

export default function ReportDocument({ project, report }) {
  return (
    <div className="mx-auto max-w-3xl bg-white p-8 text-ink-900 print:p-0">
      <div className="flex items-center justify-between border-b-2 border-navy-950 pb-4">
        <div className="flex items-center gap-3">
          <div dangerouslySetInnerHTML={{ __html: logoMark }} className="h-11 w-11" />
          <div>
            <p className="text-base font-extrabold text-navy-950">SmartManager Projects</p>
            <p className="text-xs text-ink-400">Daily Site Report</p>
          </div>
        </div>
        <div className="text-right">
          <p className="text-xs text-ink-400">Report Date</p>
          <p className="text-sm font-bold text-ink-900">{formatDate(report.report_date)}</p>
        </div>
      </div>

      <div className="mt-5 grid grid-cols-2 gap-x-6 gap-y-2 rounded-lg bg-ink-50 p-4 text-sm sm:grid-cols-3">
        <Info label="Project" value={project.name} />
        <Info label="Project Code" value={project.code} />
        <Info label="Client" value={project.client} />
        <Info label="Location" value={project.location} />
        <Info label="Weather" value={report.weather} />
        <Info label="Prepared By" value={project.project_manager} />
      </div>

      <div className="mt-6 space-y-5">
        {FIELD_ORDER.map(([key, label]) => (
          <div key={key}>
            <p className="text-xs font-bold uppercase tracking-wide text-gold-600">{label}</p>
            <p className="mt-1 whitespace-pre-line text-sm leading-relaxed text-ink-800">{report[key] || "—"}</p>
          </div>
        ))}
      </div>

      {report.photos?.length > 0 && (
        <div className="mt-6">
          <p className="text-xs font-bold uppercase tracking-wide text-gold-600">Photo Documentation</p>
          <div className="mt-2 grid grid-cols-3 gap-2">
            {report.photos.map((src, i) => (
              <img key={i} src={src} alt={`Site photo ${i + 1}`} className="h-24 w-full rounded-md border border-ink-100 object-cover" />
            ))}
          </div>
        </div>
      )}

      <div className="mt-10 border-t border-ink-100 pt-4 text-center text-[11px] text-ink-300">
        Generated by SmartManager Projects — Demo Environment · This report reflects fictional demonstration data.
      </div>
    </div>
  );
}

function Info({ label, value }) {
  return (
    <div>
      <p className="text-[11px] font-medium text-ink-400">{label}</p>
      <p className="font-semibold text-ink-800">{value || "—"}</p>
    </div>
  );
}
